on: push

defaults:
  run:
    shell: bash

jobs:
  build-windows:
    runs-on: 'windows-2022'

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Run set_version script
      uses: ./.github/actions/run-set_version_script
      with:
        venv-bin-dir: Scripts # idk why windows does this different


    - run: mkdir dist/
    - name: Download python embedded
      run: curl -L "https://www.python.org/ftp/python/3.10.7/python-3.10.7-embed-amd64.zip" -o python-embedded.zip
    - name: Unzip python embedded
      run: unzip python-embedded.zip -d dist/.python_local
    - name: Modify python embedded to allow pip to run # See https://stackoverflow.com/questions/42666121/pip-with-embedded-python
      run: rm dist/.python_local/python310._pth
    - name: Download get-pip.py
      run: curl -L "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
      working-directory: dist/.python_local
    - name: Run get-pip.py
      run: ./python.exe ./get-pip.py
      working-directory: dist/.python_local
    - name: Install requirements
      run: dist/.python_local/python.exe -m pip install --requirement requirements.txt
    - name: Copy sourcecode into dist
      run: cp -rv OATFWGUI/ dist/
    - name: Copy bootstrap script into dist
      run: cp -v scripts/OATFWGUI_Windows.bat dist/
    - name: Prune unused windows files
      run: |
        rm -v ./dist/.python_local/Lib/site-packages/PySide6/lupdate.exe || true
        rm -v ./dist/.python_local/Lib/site-packages/PySide6/Qt*Designer* || true
        rm -v ./dist/.python_local/Lib/site-packages/PySide6/Qt*Quick* || true
        rm -v ./dist/.python_local/Lib/site-packages/PySide6/Qt*Qml* || true
        rm -v ./dist/.python_local/Lib/site-packages/PySide6/Qt*Sql* || true
        rm -v ./dist/.python_local/Lib/site-packages/PySide6/Qt*Xml* || true
        rm -v ./dist/.python_local/Lib/site-packages/PySide6/linguist.exe || true
        rm -v ./dist/.python_local/Lib/site-packages/PySide6/designer.exe || true

    - name: Smoke test
      run: ./dist/OATFWGUI_Windows.bat --no-gui

    - name: Retrieve version
      id: version
      run: echo "::set-output name=VERSION::$(./dist/OATFWGUI_Windows.bat --version | tail -1)"

    - name: Remove local .platformio
      run: rm -r ./dist/.platformio
    # Work around stupid issue that GHA can't store file permissions on artifacts
    - name: Store which files are executable
      run: pushd dist/ && find . -type f -executable -print > restore_executable_permissions.txt && popd
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: OATFWGUI_${{ steps.version.outputs.VERSION }}_${{ runner.os }}_${{ runner.arch }}
        path: dist/*

  build-virtualenv:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Run set_version script
      uses: ./.github/actions/run-set_version_script

    # Fixes a bug when running the smoke test
    # https://stackoverflow.com/a/67205123
    - name: Install OpenGL
      run: sudo apt-get install freeglut3 freeglut3-dev
    - run: mkdir dist/
    - run: cp -rv OATFWGUI/ dist/
    - run: cp -v scripts/OATFWGUI_Linux.sh dist/
    - run: cp -v requirements.txt dist/

    - name: Smoke test
      run: QT_QPA_PLATFORM=offscreen ./dist/OATFWGUI_Linux.sh --no-gui

    - name: Retrieve version
      id: version
      run: echo "::set-output name=VERSION::$(./dist/OATFWGUI_Linux.sh --version | tail -1)"

    - name: Remove local .platformio
      run: rm -r ./dist/.platformio
    # Work around stupid issue that GHA can't store file permissions on artifacts
    - name: Store which files are executable
      run: pushd dist/ && find . -type f -executable -print > restore_executable_permissions.txt && popd
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: OATFWGUI_${{ steps.version.outputs.VERSION }}_${{ runner.os }}_${{ runner.arch }}
        path: dist/*

  publish-release:
    # only publish release on tags
    if: ${{ startsWith(github.ref, 'refs/tags/') == true }}
    needs: [build-windows, build-virtualenv]
    runs-on: 'ubuntu-20.04'

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Restore executable permissions
        run: |
          set -e
          shopt -s nullglob
          PERM_FILE='restore_executable_permissions.txt'
          for dir in artifacts/*/; do
            echo "Entering $dir"
            pushd "$dir"
            if [ ! -f "$PERM_FILE" ]; then
              echo "Could not find permissions file ${PERM_FILE}!"
              continue
            fi
            while IFS= read -r f_path || [ -n "$f_path" ]; do
              echo "Restoring execution on $f_path"
              chmod +x "$f_path"
            done < "$PERM_FILE"
            rm "$PERM_FILE"
            popd
          done
      - name: Zip artifacts
        run: |
          set -e
          shopt -s nullglob
          pushd artifacts/
          for dir in ./*/; do
            out_zip="../$(basename $dir).zip"
            echo "Zipping $dir into $out_zip"
            zip -8 --recurse-paths "$out_zip" "$dir"
          done
          popd
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            *.zip