on: push

jobs:
  build-pyinstaller:
    runs-on: 'windows-2022'

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Create set_version venv
      run: python -m venv .venv_set_version
    - name: set_version venv install requirements
      run: .venv_set_version/bin/pip install --requirement ./scripts/requirements_version.txt
    - name: Set version dev
      if: ${{ startsWith(github.ref, 'refs/tags/') == false }}
      run: .venv_set_version/bin/python ./scripts/set_version.py --file OATFWGUI/_version.py dev
    - name: Set version release
      if: ${{ startsWith(github.ref, 'refs/tags/') == true }}
      run: .venv_set_version/bin/python ./scripts/set_version.py --file OATFWGUI/_version.py release

    - name: Upgrade pip
      run: pip install --upgrade pip
    - name: Install requirements
      run: pip install --requirement requirements-dev.txt
    - name: Run PyInstaller
      run: pyinstaller OATFWGUI.spec

    - name: Smoke test
      run: ./dist/OATFWGUI/OATFWGUI.exe --no-gui

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: OATFWGUI_${{ runner.os }}_${{ runner.arch }}
        path: dist/*