on: push

jobs:
  build:
    runs-on: 'windows-2022'

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - run: pip3 install -U pip
    - run: pip3 install -r requirements-dev.txt
    - run: pyinstaller OATFWGUI.spec
    - uses: actions/upload-artifact@v2
      with:
        name: OATFWGUI_${{ runner.os }}_${{ runner.arch }}
        path: dist/*