on: push

jobs:
  build:
    runs-on: 'ubuntu-20.04'

    steps:
    - uses: actions/checkout@v2

    # Fixes a bug when running the smoke test
    # https://stackoverflow.com/a/67205123
    - name: Install OpenGL
      run: sudo apt-get install freeglut3 freeglut3-dev
    - run: mkdir dist/
    - run: cp -rv OATFWGUI/ dist/
    - run: cp -v scripts/OATFWGUI_Linux.sh dist/
    - run: cp -v requirements.txt dist/
    - name: Smoke test
      run: QT_QPA_PLATFORM=offscreen ./dist/OATFWGUI_Linux.sh --no-gui
    # Need to tar before upload else file permissions are lost :/
    - name: Tar files
      run: tar -cvf dist.tar ./dist
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: OATFWGUI_${{ runner.os }}_${{ runner.arch }}
        path: dist.tar